name: mdns_scout
description: An app designed to effortlessly scan your local network for services
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dynamic_color: ^1.6.9
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  easy_localization_generator: ^0.3.2
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/langs/langs.csv

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  background_color_ios: #2A2356
  image_path: "assets/icon/mdns_scout_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

