name: mdns_scout_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/mdns_scout_android.yaml"
      - "mdns_scout_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/mdns_scout_android.yaml"
      - "mdns_scout_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.13.2
      working_directory: mdns_scout_android

